### ISSUE TITLE
station naming with network or not

### ISSUE THREAD

**Issue by ShihChi90** [xumi1993/seispy#88]
**Describe the bug**
The naming of station name seem not consistant in different modules
for example in rfcorrect.py the staname is {net}.{station}
but in ccpprofile.py the staname is just station
since they both read station from same list (in ccp.cfg), this would cause some inconvinience

For example i have a station name TR01 in net TW, and my station list is also naming it TR01. 
When saving data in rfdepth, it would be named as TW.TR01. But when doing ccpstacking, it would say that the station TR01 is not in rfdepth structure. Then I would have to rename my station in list to TW.TR01, it would work as expected.

**Expected behavior**
using same config (station list) for rfdepth and ccpprofile should not cause this error

**Error raised**
2024-05-01 10:01:10,591 [CCP] WARNING: TR01 does not in RFdepth structure
![image](https://github.com/xumi1993/seispy/assets/95597521/0d637763-6a2e-4ed7-bb15-4f18b2c1d359)

**Platform (please complete the following information):**
 - Linux
 - seispy 1.3.6+ dev

**Additional context**
I think when saving data in rfdepth, just use the station name without the network.

**Comment by xumi1993** [comment]
The CCP module will read full station name from `stalist` or `stackfile`, so you need to set up the station name to `net.sta` as you have mentioned. I recommend to use commands `rf2depth` and `ccp_profile` to avoid this issue, instead of invoking modules in a python script. 

Please refer to [here](https://seispy.xumijian.me/latest/usage/ccp.html) for the standard procedure for CCP stacking.
